services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        volumes:
            - .:/var/www
    web:
        image: nginx:alpine
        container_name: web
        volumes:
            - ".:/var/www"
            - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "80:80"

    db:
        image: postgres:13
        container_name: db
        environment:
            - POSTGRES_DB=laravel
            - POSTGRES_USER=laravel
            - POSTGRES_PASSWORD=secret
        volumes:
            - ./docker/data/db:/var/lib/postgresql/data
        command: >
            bash -c "apt-get update && apt-get install -y postgis postgresql-13-postgis-3 && docker-entrypoint.sh postgres"
